before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/sfn-depends
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
nfpms:
  - id: sfn-depends-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/kanmu/sfn-depends
    maintainer: Genki Sugawara <sugawara@kanmu.co.jp>
    description: sfn-depends is a tool to check Step Functions execution result`.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
