name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md

defaults:
  run:
    shell: bash -xe {0}

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - uses: golangci/golangci-lint-action@v3
      - run: |
          make
